### ISSUE TITLE
No SetOnTextClearedLinstener for ClearableEditText

### ISSUE THREAD

**Issue by Peterragheb** [Cielsk/clearable-edittext#15]
There is no SetOnTextClearedLinstener for the ClearableEditText class.
You probably provided a fix in the latest version 0.0.6 and you didn't update your readme dependancy btw.
Also to get this fix I need to migrate to androidx which is not very pleasing.

**Comment by Cielsk** [comment]
This method is at line 174~176.
Perhaps you misspelled the name "setOnTextClearedListener" when searched the method.

**Comment by Peterragheb** [comment]
No I didn't the method is not available in the version 0.0.5 only in 0.0.6 which i need to migrate to android x to get.
Please provide a lib version that doesn't require migration.

**Comment by Cielsk** [comment]
Now you can try to use the version 0.0.5-fix1:
`implementation 'com.github.Cielsk:clearable-edittext:0.0.5-fix1'`

**Comment by Peterragheb** [comment]
Thank you :D
