### ISSUE TITLE
android:drawableStart not working

### ISSUE THREAD

**Issue by vipulim** [Cielsk/clearable-edittext#18]
Hello

I want to set a search icon on the left side of the edit text but the attribute   `android:drawableStart="@drawable/ic_search"` isn't working, It doesn't display the search icon.

Anything I'm missing?

**Comment by Cielsk** [comment]
You can try [version 0.0.7](https://github.com/Cielsk/clearable-edittext/releases/tag/0.0.7), which fixed this bug.

**Comment by vipulim** [comment]
Seems like it only works for `android:drawableEnd` and not for `android:drawableStart`.
I guess to get drawable start you need to use the` getCompoundDrawablesRelative` method instead of  `getCompoundDrawables`.

I tried to get drawable start using `getCompoundDrawablesRelative` but it's not reflecting on UI. Still checking.

**Comment by Cielsk** [comment]
Perhaps you can use both `android:drawableLeft` and `android:drawableStart` to set the search icon.

If it does work, [version 0.0.8](https://github.com/Cielsk/clearable-edittext/releases/tag/0.0.8) will fix the bug(it use `getCompoundDrawablesRelative` and `setCompoundDrawables` when build sdk version is not less than 17).
