### ISSUE TITLE
Invoking OnTextClearedListener in tests

### ISSUE THREAD

**Issue by cheskos** [Cielsk/clearable-edittext#19]
Hi.

I need to test a couple of screens with Robolectric, and I don't see a way to test the logic I put under the OnTextClearedListener. Am I missing something?

Thanks!

**Comment by Cielsk** [comment]
Unfortunately there is still no easy way to do that.

As the "clear icon" is actually just a drawable not a button with resource id, it is not easy to handle drawable clicking event with Robolectric.

You may try it with Espresso(Instrumentation Testing).
