### ISSUE TITLE
Lost EditText value after orientation changed

### ISSUE THREAD

**Issue by DonMat** [Cielsk/clearable-edittext#3]
Steps to reproduce:

1. Run demo app and fill the field
2. Change orientation
3. Values disappeared

**Comment by Cielsk** [comment]
Thank you for reminding me.
I forgot to add id to EditText.

**Comment by DonMat** [comment]
See my fork. I added some improvements which I can PR if you want ;)

**Comment by Cielsk** [comment]
Yes, I mean why not.
It's good of you to do it 👍
