### ISSUE TITLE
attribute not found

### ISSUE THREAD

**Issue by 97balakrishnan** [Cielsk/clearable-edittext#6]
I am getting this error when trying to add customisation to the clearable-edittext.
Its working fine without these.

Error:error: attribute 'com.example.balakrishnan.mybrowser:clearIconDrawWhenFocused' not found.
Error:attribute 'com.example.balakrishnan.mybrowser:clearIconDrawWhenFocused' not found.

**Comment by Cielsk** [comment]
Version 0.0.4 fixed this bug, then you can :

1. upgrade to 0.0.4
2. clear project
3. rebuld project or run app

Hope this will help you.

**Comment by 97balakrishnan** [comment]
Thanks :)
