### ISSUE TITLE
Attribute 'clearIconDrawWhenFocused' not found.

### ISSUE THREAD

**Issue by yehlfektn** [Cielsk/clearable-edittext#7]
Hello, 

Compiled the last version 
compile 'com.github.Cielsk:clearable-edittext:0.0.3'

but it can not find the attribute clearIconDrawWhenFocused, 

I need that to appear the drawable, when the view is focused.

**Comment by Cielsk** [comment]
Version 0.0.4 fixed this bug, then you can :

1. upgrade to 0.0.4
2. clear project
3. rebuld project or run app

Hope this will help you.
